name: Auto Assign
on:
  issues:
    types: [opened, edited]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign
        uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/auto-assign.yml
