name: Auto Assign
on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign
        uses: wow-actions/auto-assign@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-assignees: "niiicolai, mads94i5, ThomasSA-Git"
